- name: Create user and group and fetching something
  hosts: rocky
  become: true
  tasks:
    - name: Create group
      group: 
        name: practice_group
        state: present


    - name: Create user
      user:
        name: practice
        group: practice_group
        
    - name: Fetching data
      fetch:
        src: /home/ansible/hello.txt
        dest: /tmp/
